In [1]:
import pandas as pd
from pathlib import Path

In [2]:
df=pd.read_csv('google_hourly_search_trends.csv', index_col='Date', parse_dates=True, infer_datetime_format=True)

In [13]:
df_g=df.groupby(by=[df.index.year, df.index.month]).sum()

In [14]:
df_g

           Search Trends
Date Date
2016 6             33196
     7             33898
     8             34459
     9             32376
     10            32334
     11            33793
     12            33789
2017 1             32984
     2             31901
     3             35363
     4             32522
     5             33216
     6             34211
     7             34988
     8             36113
     9             33693
     10            32842
     11            35144
     12            35420
2018 1             37347
     2             33748
     3             36051
     4             35283
     5             35309
     6             34115
     7             35927
     8             37012
     9             34037
     10            35879
     11            34686
     12            35245
2019 1             38505
     2             34129
     3             37331
     4             35505
     5             34983
     6             36120
     7             37089
     8             37540
     9             35201
     10            37212
     11            36280
     12            37825
2020 1             39177
     2             30838
     3             24805
     4             35229
     5             38181
     6             35758
     7             35620
     8             33530
     9              8126